=== gxldnn/edt2/Llenguatje de Marques/AC2/Ex3.dtd
<!ELEMENT comanda (client, productes, pagament)>
<!ATTLIST comanda num CDATA #REQUIRED>
<!ELEMENT client (nom,adreça)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT adreça (#PCDATA)>
<!ELEMENT productes (producte*)>
<!ELEMENT producte (nom,preu)>
<!ATTLIST producte codi ID #REQUIRED>
<!ATTLIST producte quantitat CDATA #REQUIRED>
<!ELEMENT preu (#PCDATA)>
<!ELEMENT pagament (#PCDATA)>

=== gxldnn/edt2/Llenguatje de Marques/XML/AC2/Ex3.xml
<!DOCTYPE comanda SYSTEM "Ex3.dtd">
<comanda num="2025-001">
    <client>
        <nom>Maria López</nom>
        <adreça>C/ Major 45, Barcelona</adreça>
    </client>
    <productes>
        <producte codi="P1001" quantitat="2">
            <nom>Cafetera</nom>
            <preu>49.99</preu>
        </producte>
        <producte codi="P2003" quantitat="1">
            <nom>Torradora</nom>
            <preu>29.50</preu>
        </producte>
    </productes>
    <pagament tipus="Targeta"></pagament>
</comanda>
