=== gxldnn/edt2/Llenguatje de Marques/AC2/Ex4.dtd
<!ATTLIST enguany value (2025) #REQUIRED>
<!ELEMENT revista (article+)>
<!ELEMENT article (titol, autor, cos, etiquetes)>
<!ATTLIST article id ID #REQUIRED>
<!ELEMENT titol (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT cos (#PCDATA)>
<!ELEMENT etiquetes (etiqueta+)>
<!ELEMENT etiqueta (#PCDATA)>

=== gxldnn/edt2/Llenguatje de Marques/AC2/Ex4.xml
<!DOCTYPE revista SYSTEM "Ex4.dtd" [<!ENTITY enguany "2025">]>
<revista>
    <article id="A1">
        <titol>La intel·ligència artificial avui</titol>
        <autor>Laura Riera</autor>b
        <cos>Publicat l'any &enguany;.</cos>
        <etiquetes>
            <etiqueta>tecnologia</etiqueta>
            <etiqueta>IA</etiqueta>
        </etiquetes>
    </article>
</revista>
